import { Button } from "./_button.js";
import { Form } from "./_form.js";
import { Navbar } from "./_navbar.js";
import { Slider } from "./_slider.js";
import { Modal } from "./_modal.js";
import { Tab } from "./_tab.js";
import { Tagger } from "./_tagger.js";
import { Carousel } from "./_carousel.js";
import { Gallery } from "./_gallery.js";
import Stack from "./components/stack.js";
import Rating from "./components/rating.js";

window.Slider = Slider;
window.Modal = Modal;
window.Tab = Tab;
window.Tagger = Tagger;
window.Carousel = Carousel;
window.Gallery = Gallery;
window.Stack = Stack;
window.Rating = Rating;
